### PR TITLE
Be a good unix-gopher user, work with stdin/stdout streams too

### PR DESCRIPTION
**Pull request by kron4eg**
Added default fallback to IO streams if input/output files are not specified.

### CODE REVIEW

**Comment by oschwald** [comment]
Supporting stdin and stdout seems like a good idea, but I think I might prefer if it was explicit rather than the default behavior.

**Comment by kron4eg** [comment]
@oschwald like `-block-file=- output-file=-`?

**Comment by kron4eg** [comment]
I guess my thought was that for existing users nothing will change, all flags will work the same way. But for those who want shell piping it will save flags typing.

I've already used that personally while prepared import in sqlite database (too lazy to convert CIDR to ranges in shell :D). I've piped original Cities db into this, for CIDR to IP ranges conversion and filtered out some fields and imported result in sqlite. All without buffering stages to disk.

**Comment by oschwald** [comment]
My concern is that people will be confused when they forget `-block-file=` and, from their perspective, the program hangs. Requiring an explicit flag is fairly standard, e.g., `gzip -c`.

**Comment by kron4eg** [comment]
@oschwald OK, suppose I've added `-c`, that's for stdout. What about stdin?

**Pull request closed without merging**
